### ISSUE TITLE
Удаление контента из табличного списка после изменений в КБ

### ISSUE THREAD

**Issue by Ormanko** [nikolaiav/mpsiemlib#1]
Николай, здравствуйте.

Попробовал в работе библиотеку mpsiemlib. 
Удобно, интересно, но возник вопрос - в случае если заполнять табличный список типа справочник, то любые изменения в КБ, которые не касаются данного табличного списка, обнуляют загруженный через скрипт контент. 

То есть:
1. Внес скриптом записи
2. Проверил они есть
3. Взял другое правило (тут в принципе не суть важно что, главное не сам табличный список) в КБ и просто его (только его) проинсталлировал в сием
4. Проверил записи в нужном табличном списке - пропали

С табличным списком типа репутационный список такого нет. 

Скажите это фича или нужно что-то сделать дополнительно?

**Comment by Ormanko** [comment]
Забыл добавить - версия 24.1

**Comment by nikolaiav** [comment]
Добрый день.
При установке любого контента из КБ в SIEM автоматом еще и обновятся справочники и реп. списки в SIEM.
Т.о. справочники менять надо не в SIEM, а KB. 
MP SIEM работает так:
- В КB есть справочники/реп списки/заполняемые правилами корр. и обогащением.
- При инсталляции в SIEM они превращаются в табличные списки.
- Есть отдельное API для работы с этими объектами на уровне KB и есть отдельное API для работы с ними в SIEM.
- SDK работает с табличными списками на уровне самого SIEM.  

К сожалению в текущей версии SDK не умеет редактировать справочники в KB, но умеет выгружать их содержимое.  
В вашем случае можно создать не справочник, а табличный список, заполняемый корр. или правилами обогащения.
Это позволит менять их содержимое не боясь, что любая установка контента из KB перетрет записи.
При таком подходе работать с записями вручную надо будет не в интерфейсе KB, а интерфейсе MP SIEM.

**Comment by Ormanko** [comment]
Николай, благодарю. 
До такого варианта пока не додумался... попробую.
